---
:ems:
  :ems_redhat:
    :use_ovirt_engine_sdk: true
    :resolve_ip_addresses: true
    :inventory:
      :read_timeout: 1.hour
      :open_timeout: 1.minute
    :service:
      :read_timeout: 1.hour
      :open_timeout: 1.minute
  :ems_ovirt:
    :blacklisted_event_names: []
    :event_handling:
      :event_groups:
    :connection_manager:
      :purge_interval: 1.hour
:http_proxy:
  :ovirt:
    :host:
    :password:
    :port:
    :user:
:ems_refresh:
  :rhevm:
    :inventory_object_refresh: false
