---
:ems:
  :ems_ovirt:
    :blacklisted_event_names: []
    :event_handling:
      :event_groups:
    :connection_manager:
      :purge_interval: 1.hour
:http_proxy:
  :ovirt:
    :host:
    :password:
    :port:
    :user:
:ems_refresh:
  :rhevm:
    :inventory_object_refresh: false
