---
:ems:
  :ems_redhat:
    :product_version_to_api_version_regexps:
      :'^3\..*$': 3
      :'^4\..*$': 3 4
    :use_ovirt_engine_sdk: true
    :resolve_ip_addresses: true
    :inventory:
      :read_timeout: 1.hour
      :open_timeout: 1.minute
    :service:
      :read_timeout: 1.hour
      :open_timeout: 1.minute
    :blacklisted_event_names: []
  :ems_ovirt:
    :ems_network:
      :refresh:
        :inventory_object_refresh: true
    :event_handling:
      :event_groups:
        :network:
          :critical:
          - network.create.end
          - network.delete.end
          - network.update.end
          - subnet.create.end
          - subnet.delete.end
          - subnet.update.end
    :connection_manager:
      :purge_interval: 1.hour
:http_proxy:
  :rhevm:
    :host:
    :password:
    :port:
    :user:
:ems_refresh:
  :rhevm:
    :inventory_object_refresh: false
    :pipeline: 40
    :connections: 10
:log:
  :level_rhevm: info
:workers:
  :worker_base:
    :event_catcher:
      :event_catcher_redhat:
        :poll: 15.seconds
      :event_catcher_redhat_network:
        :poll: 15.seconds
        :topics:
          :neutron: "notifications.*"
        :duration: 10.seconds
        :capacity: 50
        :amqp_port: 5672
        :amqp_heartbeat: 30
        :amqp_recovery_attempts: 4
        :ceilometer:
          :event_types_regex: '\A(firewall|floatingip|gateway|net|port|router|subnet|security_group|vpn)'
    :queue_worker_base:
      :ems_metrics_collector_worker:
        :ems_metrics_collector_worker_redhat: {}
        :ems_metrics_collector_worker_redhat_network: {}
      :ems_refresh_worker:
        :ems_refresh_worker_redhat: {}
        :ems_refresh_worker_redhat_network: {}
