---
:ems:
  :ems_redhat:
    :use_ovirt_engine_sdk: true
    :resolve_ip_addresses: true
    :inventory:
      :read_timeout: 1.hour
      :open_timeout: 1.minute
    :service:
      :read_timeout: 1.hour
      :open_timeout: 1.minute
    :blacklisted_event_names: []
  :ems_ovirt:
    :event_handling:
      :event_groups:
    :connection_manager:
      :purge_interval: 1.hour
:http_proxy:
  :rhevm:
    :host:
    :password:
    :port:
    :user:
:ems_refresh:
  :rhevm:
    :inventory_object_refresh: false
:log:
  :level_rhevm: info
:workers:
  :worker_base:
    :event_catcher:
      :event_catcher_redhat:
        :poll: 15.seconds
    :queue_worker_base:
      :ems_metrics_collector_worker:
        :ems_metrics_collector_worker_redhat: {}
      :ems_refresh_worker:
        :ems_refresh_worker_redhat: {}
